services:
  dev:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: sh -c "yarn install && yarn build && yarn dev"
